import { expect, test } from '@playwright/test';
import { openApp, openPrimaryView, expectNoHorizontalOverflow } from './helpers';

test('applies last month spending explicitly and shows separate actual spending stacks', async ({ page }) => {
  await page.clock.install({ time: new Date(2026, 8, 15, 12) });
  await openApp(page);
  await openPrimaryView(page, 'Transactions');
  const form = page.locator('.transaction-form');
  await form.getByRole('button', { name: 'Enter manually' }).click();
  await form.getByLabel('Date', { exact: true }).fill('2026-08-10');
  await form.getByLabel('Category').selectOption('Food');
  await form.getByLabel('Description').fill('Groceries');
  await form.getByLabel('Amount', { exact: true }).fill('123.45');
  await form.getByRole('button', { name: 'Save transaction' }).click();
  await openPrimaryView(page, 'Budget');
  await page.getByLabel('VIEW MONTH').fill('2026-09');
  await expect(page.getByLabel('Food expected monthly budget')).toHaveValue('');
  await page.getByRole('button', { name: 'Use Food recommendation: $123.45' }).click();
  await expect(page.getByLabel('Food expected monthly budget')).toHaveValue('123.45');
  await expect(page.getByRole('button', { name: 'Apply all recommendations' })).toBeVisible();
  await page.getByRole('button', { name: 'Apply all recommendations' }).click();
  await page.getByLabel('VIEW MONTH').fill('2026-11');
  await expect(page.locator('.budget-recommendations')).toContainText('No eligible spending');
  await page.getByLabel('VIEW MONTH').fill('2026-08');
  await page.getByRole('button', { name: 'Scheduled payments', exact: true }).click();
  const schedule = page.locator('.recurring-form');
  await schedule.getByLabel('Name', { exact: true }).fill('Rent');
  await schedule.getByLabel('Amount').fill('400');
  await schedule.getByLabel('First charge month').fill('2026-08');
  await schedule.getByRole('button', { name: /Add monthly payment/ }).click();
  await openPrimaryView(page, 'Transactions');
  await form.getByRole('button', { name: 'Enter manually' }).click();
  await form.getByLabel('Count toward monthly budget').uncheck();
  await form.getByLabel('Link to a scheduled cost').check();
  await form.getByLabel('Scheduled payment').selectOption({ index: 1 });
  await form.getByLabel('Date', { exact: true }).fill('2026-08-12');
  await form.getByRole('button', { name: 'Save transaction' }).click();
  await openPrimaryView(page, 'Insights');
  await page.getByLabel('Analysis through month').fill('2026-08');
  const bar = page.locator('.trend-bars > div').last();
  await expect(bar).toHaveAttribute('aria-label', /Scheduled payments \$400.00.*Flexible spending \$123.45/);
  await expect(bar.locator('.trend-bar-values')).toContainText('$400.00 scheduled');
  await expect(bar.locator('.trend-bar-values')).toContainText('$123.45 flexible');
  await expect(page.locator('.insight-kpis')).toHaveCount(0);
  await expect(page.locator('.insight-action-copy')).toHaveCount(0);
  await expect(bar.locator('.trend-scheduled')).toBeVisible();
  await expect(bar.locator('.trend-flexible')).toBeVisible();
  expect(await bar.locator('.trend-scheduled').evaluate(el => getComputedStyle(el).backgroundColor)).not.toEqual(await bar.locator('.trend-flexible').evaluate(el => getComputedStyle(el).backgroundColor));
  await expectNoHorizontalOverflow(page);
});
